const MOVIE_FETCH_START = 'MOVIE_FETCH_START'
const MOVIE_FETCH_SUCCESS = 'MOVIE_FETCH_SUCCESS'
const MOVIE_FETCH_ERROR = 'MOVIE_FETCH_ERROR'

const movieTypes = {
  MOVIE_FETCH_START,
  MOVIE_FETCH_SUCCESS,
  MOVIE_FETCH_ERROR
}

export default movieTypes