const MOVIES_FETCH_START = 'MOVIES_FETCH_START'
const MOVIES_FETCH_SUCCESS = 'MOVIES_FETCH_SUCCESS'
const MOVIES_FETCH_ERROR = 'MOVIES_FETCH_ERROR'
const MOVIES_GENRES_CHANGED = 'MOVIES_GENRES_CHANGED'
const MOVIES_CLEAR_ALL_GENRES = 'MOVIES_CLEAR_ALL_GENRES'

const moviesTypes = {
  MOVIES_FETCH_START,
  MOVIES_FETCH_SUCCESS,
  MOVIES_FETCH_ERROR,
  MOVIES_GENRES_CHANGED,
  MOVIES_CLEAR_ALL_GENRES
}

export default moviesTypes